# Generated by Django 6.0.3 on 2026-09-17 17:15

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, validators=[users.models.validate_cyrillic], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[users.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
